services:
  # NGINX proxy
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/cert.pem:/ssl/cert.pem
      - ./certs/key.pem:/ssl/key.pem
      - ./logs:/logs
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=10.0.0.4
    links:
      - graylog

  # MongoDB
  mongo:
    image: mongo:4.2
    networks:
      - graylog
    volumes:
      - mongo_data:/data/db
  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
  # Graylog
  graylog:
    image: graylog/graylog:4.3.0
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=JsIMIwHCgAVqPA1ND5y7Nd1J20neATBNzUdTkikirw7gw5L1HC1G9rN7fFxA9HIYUIBptZ03N5h7JVQuQZeuI46TavgzhV04
      # Username/Password: admin/admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://10.0.0.4:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
    # Windows log from Winlogbeat are sent to port 5044
      - 5044:5044
      - 5044:5044/udp
     # Graylog web interface and REST API
      - 9000:9000
     # Syslog TCP
      - 1514:1514
     # Syslog UDP
      - 1514:1514/udp
     # GELF TCP
      - 12201:12201
     # GELF UDP
      - 12201:12201/udp
networks:
  graylog:
    driver: bridge
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local
